### ISSUE TITLE
feature request: move `as` to its own keyword

### ISSUE THREAD

**Issue by elianiva** [Himujjal/tree-sitter-svelte#1]
Hi there! I really appreciate the work you've put into this parser and I absolutely love it. I have an issue though. Is it possible to separate the keyword `as` from `raw_text_expr` ? Consider this snippet.

```svelte
{#each $jobs as { created_at, title, type, company, location, company_logo, id }}
```

The `$jobs as { created_at, title, type, company, location, company_logo, id }` will get parsed as `raw_text_expr`.
I use `javascript` parser to handle those bits, since `as` is not a valid javascript keyword, it throws an error. My idea is to make `{#each foo as bar}` where `foo` and `bar` is a `raw_text_expr` but make `as` a keyword similar to `if_tag` or `else_tag`.

Here's a rough representation of how the tree would look like.

```scheme
(special_block_start
  (each_tag)
  (raw_text_expr)
  (as_keyword) ;not sure about the name
  (raw_text_expr))
```

This doesn't cause any big impact, it still works fine but having a keyword that isn't a valid javascript syntax to be placed inside `raw_text_expr` isn't ideal IMO

edit: I found another one which is `{@html ...}`, I think we should make `@html` as a keyword.

Thanks!

**Comment by Himujjal** [comment]
This is interesting. You could maybe pull up tree-sitter-javascript, make slight bit of changes and make `as` a keyword. Well. I already did it.

https://github.com/Himujjal/tree-sitter-js-svelte

As operator:
https://github.com/Himujjal/tree-sitter-js-svelte/blob/master/grammar.js#L798

Destiny statement:
https://github.com/Himujjal/tree-sitter-js-svelte/blob/master/grammar.js#L345

**Comment by elianiva** [comment]
Ah, that looks good. But is it not possible to change add it here? Since `as` is not a keyword in Javascript and I think `tree-sitter-javascript` follows the ECMA standard.

**Comment by Himujjal** [comment]
>  found another one which is {@html ...}, I think we should make @html as a keyword.

This latest commit should do the work.

https://github.com/Himujjal/tree-sitter-svelte/commit/c92c46d8b3e4a9d67e2059c4916e7253a001de06

But there is one catch:
`{@html someString }` will be parsed as `(html_block (raw_expr))` but `{ @html someString}` will be parsed as `(raw_expr)`. The extra space will need some C code to be modified in `src/scanner.c`. But for now, this should do the work.

**Comment by elianiva** [comment]
I will try that tomorrow, thanks! :)

**Comment by Himujjal** [comment]
> Ah, that looks good. But is it not possible to change add it here? Since `as` is not a keyword in Javascript and I think `tree-sitter-javascript` follows the ECMA standard.

Probably. I think it would be better if we maintain a fork of tree-sitter-javascript updating the extra repo to commits in `tree-sitter-javascript`. Destiny statements support will be a plus in case Svelte decides to do something extra regarding that. I will maintain the extra repo BTW in case you are thinking of the extra effort. I am already on another project building a language (subset of TypeScript) using Tree-sitter, so I am already closely monitoring `tree-sitter-javascript`

BTW I have made a new change. Now, `{someVariable}` will be represented as `(expression (raw_text_expr))` and `{@html string}` will be `(expression (raw_text_expr))`. Fixed the `@html` problem.

**Comment by elianiva** [comment]
I think I'd agree with you. I tried making `as` to its own keyword but it broke because there's a variable name with `as` as part of its name in Javascript.

**Comment by Himujjal** [comment]
Hey. I did the `as` thing you asked for. I will update the master branch soon enough.

Also, there was `then` keyword for await statement. That is also done.

**Comment by elianiva** [comment]
oh, thanks!
