### ISSUE TITLE
Add support for :each in #each blocks

### ISSUE THREAD

**Issue by Himujjal** [Himujjal/tree-sitter-svelte#13]
https://svelte.dev/docs#each

`#each` blocks also have a `:else` block which is used to render if the list is empty. Implement that!

**Comment by Himujjal** [comment]
@elianiva Hey. I fixed this issue. Can you check if the queries are still alright and merge it in the neovim repo?

**Comment by elianiva** [comment]
I can test it tonight, sorry for the late reply!
