### ISSUE TITLE
feature request: treat any node between special block as its childnode

### ISSUE THREAD

**Issue by elianiva** [Himujjal/tree-sitter-svelte#2]
I think it would be better if a node between `special_block` is treated as its childnode. Consider the following snippet

```svelte
{#if something}
  <div></div>
{:else}
  <div></div>
{/if}
```

Both `<div />` element will be considered as a sibling node instead of `special_block`'s childnode. Treating them as a childnode makes more sense in my opinion, similar to how `if else` expression in Javascript where anything inside `{}` is treated as a childnode.

I rely on this for `indent` feature that `nvim-treesitter` has. I don't know how hard is this to implement so if it's not possible then feel free to close this issue :)
Thanks in advance!

**Comment by Himujjal** [comment]
This is an important feature. I am working on this one right now. Hi. Can you hold on to nvim-treesitter for some time. I am stuck on nested if-else statements in the grammar. Asked for help.

**Comment by elianiva** [comment]
Sure, no need to rush :)
An sorry if I couldn't help because I don't know much about TS grammar.

**Comment by Himujjal** [comment]
Hey. I got one part of that working. But I don't think that should be of any good to your case. The nesting is way off the way it should be.

```svelte
{#if something}
  <div></div>
{:else if someOtherThing}
  <div></div>
  {#if something}
  <div></div>
  {:else if someOtherThing}
    <div></div>
  {:else}
    <div></div>
  {/if}
{:else}
  <div></div>
{/if}
```
should produce the following text:
```scm
(document
    (if_statement (if_start_expr (raw_text_expr)) (text)
        (else_if_statement (else_if_expr (raw_text_expr)) (text)
            (if_statement (if_start_expr (raw_text_expr)) (text)
                (else_if_statement
                    (else_if_expr (raw_text_expr)) (text)
                    (else_statement (else_expr) (text) (if_end_expr)
                    )  
                )
            ) (text)
            (else_statement (else_expr) (text)
                (if_end_expr)
            )
        )
    )
)
```
Where the if_end_expr is way nested than it should be. Should this be a good output? If yes. Then I will commit the latest change. For reference, I was referring to tree-sitter-lua whose `if-else-end` is similar to `if-else` in Svelte. Yet, I am finding it hard to produce similar output.

**Comment by elianiva** [comment]
That's good enough, I think. I can't fully confirm yet but I'll try it tomorrow. Thanks for the hard work!

**Comment by Himujjal** [comment]
Man I give up on the if-else thing for now. I am still unsure what can be done to improve upon this. This was just a side project anyways. I will put this same algorithm elsewhere for await-then-catch and be done with it. html element thing is done.

I dont think anything else is left. Everything seems to be done for now.

I will update the master branch. For the neovim thing do you have a repo that you are working on?

**Comment by elianiva** [comment]
no, I don't have a repo for that. Though I save them [here](https://github.com/elianiva/dotfiles/tree/master/nvim/.config/nvim/after/queries/svelte) along with my dotfiles.

anyway, feel free to close this. I can still use the old indent method without treesitter. You've done an awesome work and I don't want to push you.

**Comment by Himujjal** [comment]
I have pushed my code to the master branch and to npm. You can use that if you want. If anyone in the future finds a workaround to the if-else-elseif problem as stated in the README.md he/she will probably correct it.

Anyways, with this, I rest my work here. Let this issue be open. I will post about this repo on neovim subreddit so that anyone can jump in and maybe work on it. Till then goodbye.

**Comment by elianiva** [comment]
you know what, this is perfect! I just tried it and the result is exactly what I want. I don't know if we should close this issue but I am satisfied with the result. Thank you!

**Comment by Himujjal** [comment]
You can do whatever you want.  Close this issue. Open this issue. Its upto you. If your work is done. Close it. If not, keep it open. :D

**Comment by elianiva** [comment]
alright then.
