### ISSUE TITLE
Minor inconsistencies with indenting

### ISSUE THREAD

**Issue by pmrt** [Himujjal/tree-sitter-svelte#23]
Hi, thanks for maintaining this package. Tree-sitter is awesome!

I'm getting into svelte and I noticed minor inconsistencies but I'm not sure if it is because of this module. I'm using neovim with treesitter and lsp and have installed this language for treesitter so I think I'm in the right place, the indenting is coming from treesitter, I guess.

Now, to the point:
![Untitled](https://user-images.githubusercontent.com/22831717/155988230-ce1abf50-c60d-45df-a55e-ec849f366c2e.gif)

_Notice how:_
(A) When my cursor is under `<script>` tag, the next line is not automatically indented. It is not considered a child node (sorry, I don't know the exact terminology you guys use for this since I'm not into this). The same goes for `<style>` tag.
(B) When my cursor is under the html tag `<main>`, the next line is automatically indented. Indenting works as expected.
(C) When you're already in an indented child node, the indenting works as expected for the next line.

I think these are minor inconsistencies that thanks to (C) shouldn't be considered as a priority, but as a QoL update it would be great to have them fixed.

Am I in the right place reporting this here? Maybe this is the intended behavior?

**Comment by Himujjal** [comment]
Thanks for reporting this issue.

Actually anything other than xml like syntax is parsed as raw text. So, basically when you go from XML to raw text (`css` or `js`), it like starting from the beginning of a new (`css`, `js`) file. Thus the indentation won't behave normally in that case.

I have an idea to fix this, but it will be like really really messy and time consuming. What do you say? Is it worth the effort, or let's leave it as it may be?

**Comment by pmrt** [comment]
Oh, I thought it would be just something like indenting the raw text in the queries when it is right after xml or something like that. I would help but I know nothing about how this works so I'd end up spending twice or three times the time it'd take you to fix it, just for learning it.

I'd say leave it for now because it's just for the first line. When you're coding it's not about creating new scripts or styles blocks most of the time, but editing existing ones. Also, **if you use prettier with svelte plugin it will fix the indenting, so if anyone is bothered enough by this I recommend using and configure it to format your code when saving as a workaround**.

Maybe label this issue as enhancement or something like that for the long-term, and if you come up with a simpler idea on how to solve it or you feel like it one day that would be great, but definitely not as priority. That way someone even can PR this if he/she comes up with a better idea! (But I'm afraid this is one of those 'underhood' sub-packages that everyone uses and needs in their editors but no one knows about it, so if indenting fails most won't even know where it is coming from)

**Comment by Himujjal** [comment]
Cool. Would do that. I would keep this issue open then. Welcome anyone with the PR. Thanks for this though. I am sorry, I just think its not worth the effort. Might as well break something else.

Meanwhile, if I get time, I will look over tree-sitter-html from where I derived 60% of my code. I use prettier all the time, so you know it rarely affects my workflow. Anyways, I never maintain formatting while coding, simply using `<leader>ft` to call [Neoformat](https://github.com/sbdchd/neoformat).

**Comment by Himujjal** [comment]
@elianiva Anything that can be done on the queries part on this issue?
This is related to the raw text part of the TS lib

**Comment by elianiva** [comment]
hmm, this is a bit hard

I made it to work this way because I don't like indenting the script and style tag (there's also an option on prettier for this behaviour, see https://github.com/sveltejs/prettier-plugin-svelte#svelte-indent-script-and-style).
I don't think we can make that configurable like how they do it in https://github.com/leafOfTree/vim-svelte-plugin#configuration since query file is not configurable.

We could probably change it to make it behave like `svelte-indent-script-and-style` set to `true` if people prefer it that way, but there are probably some users (like me) who prefer the current behaviour. I'm fine either way since I don't really use Neovim that much anymore.

What do you think?

**Comment by Himujjal** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/2779 will solve this.

Please try doing `:PackerUpdate` and `:TSUpdate` in neovim after the above PR will be resolved

**Comment by Himujjal** [comment]
Fixed in the latest update. Please update packer and tree-sitter

**Comment by login6** [comment]
> Fixed in the latest update. Please update packer and tree-sitter

Sorry for stupid question. But how can i achieve indentation in the first lines in tags with @indent capture?
