### ISSUE TITLE
The dot character in component's name breaks the highlighting

### ISSUE THREAD

**Issue by AnatoleLucet** [Himujjal/tree-sitter-svelte#25]
Hi :wave:. It seems like having a `.` (dot) in a component name, breaks the highlighting (especially the css).

![](https://user-images.githubusercontent.com/35486736/161433202-579daf0d-b8d6-464d-9766-27bdc6fcb10d.gif)

For some reason, the `.Root` doesn't seem to have the correct highlighting, and the css's is fully absent (although I seem to be able to "fix" it when adding/removing a level of indentation).

**Comment by Himujjal** [comment]
Okay. This is a real issue. Will fix this in the next iteration. Thanks for finding this out

**Comment by Himujjal** [comment]
https://github.com/Himujjal/tree-sitter-svelte/releases/tag/v0.10.0

Fixes this
