### ISSUE TITLE
Error when querying with nvim-treesitter: Invalid node type at position 5 for language svelte 

### ISSUE THREAD

**Issue by stefanwatt** [Himujjal/tree-sitter-svelte#31]
```
  local tsparser = vim.treesitter.get_parser(0, "svelte")
  local root = tsparser:parse()[1]:root()
  local query = vim.treesitter.parse_query('svelte', [[
    (identifier) @var
  ]])
  for id, captures, metadata in query:iter_matches(root,0) do
    i(captures)
  end

```
Running the above lua code in neovim results in the error described in the title.
The same snippet works fine when replacing the language, so I assume it's not an issue with nvim-treesitter.
I will gladly provide any information that I can if needed.

**Comment by Himujjal** [comment]
I don't know too much about the `vim.treesitter` api but can you please share a piece of code that could help me run a query to see if the grammar is alright.

**Comment by stefanwatt** [comment]
That's a shame. I thought neovim was the main use case for treesitter.
You can run the lua snippet inside neovim.
Not sure what kind of code snippet you would want.

**Comment by Himujjal** [comment]
I will look into it further. I built tree-sitter-svelte for Neovim and for a working Svelte parser to be fair. Both cases.

**Comment by stefanwatt** [comment]
> I just tried using the treesitter cli, which seems to work with the svelte grammar.
> Queries don't error out and return results that make sense.

Actually, I have to take that back. The CLI returns a different syntax tree.
Querying for "identifier" also doesn't work, but in this case it actually makes sense as there is no "identifier" nodes shown in the parser output.

For both CLI and vim.treesitter query the following query works.
`(tag_name) @var`

**Comment by Himujjal** [comment]
@stefanwatt This has to be patched the [nvim-treesitter/nvim-treesitter](github.com/nvim-treesitter/nvim-treesitter) repo queries.

I can help with that. Can you provide me specific piece of code?
