### ISSUE TITLE
tree-sitter-css doesn't highlight correctly

### ISSUE THREAD

**Issue by sammce** [Himujjal/tree-sitter-svelte#32]
The https://github.com/tree-sitter/tree-sitter-css grammar parser, for whatever unfathomable reason, marks the class selectors, CSS properties and various other things the same colour. See https://github.com/tree-sitter/tree-sitter-css/issues/34 for photo examples. [This issue](https://github.com/Himujjal/tree-sitter-svelte/issues/30) on this repo implies that the treesitter-css parser is the only one that works with the svelte parser.

My question: is there any way for me to use the default CSS parser instead of the treesitter one? The default CSS syntax highlighting is exactly how I want it to look, but it's physically impossible to replicate it with the treesitter-css parser.

BTW: Loving this parser in all other facets, great work!

**Comment by Himujjal** [comment]
I think this is not possible. BTW, are you using this for Neovim or just for parsing? I can help though

**Comment by Himujjal** [comment]
@sammce Did you try ":TSInstall scss css" in neovim?
