### ISSUE TITLE
Is it possible to use `<style lang="postcss">`?

### ISSUE THREAD

**Issue by rstacruz** [Himujjal/tree-sitter-svelte#33]
Thank you so much for this package!

I found that using `<style lang="anything-here">` will turn off syntax highlighting in Neovim. When using Tailwind with Svelte, it seems to be recommended to use lang="postcss" [to prevent reporting errors about unknown at rules](https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-2881908).

Is there any workaround for this?

<table>
<tr>
<th>Without</th>
<th>With</th>
</tr>
<tr>
<td>

![image](https://user-images.githubusercontent.com/74385/215064342-1f3a1070-db41-4a8b-b456-8ed1ed59c715.png)

</td>
<td>

![image](https://user-images.githubusercontent.com/74385/215064420-86cc33a3-54ea-405a-b55a-a32a359a9715.png)

</td>
</tr>
<tr><td>

Without `lang="postcss"`, syntax highlighting works, but svelte-language-server reports errors when using Tailwind syntax.

</td><td>

With `lang="postcss"`, syntax highlighting doesn't work.

</td></tr>
</table>

**Comment by ajuvercr** [comment]
I have the same issue with `<script lang="ts">`, any updates on this?

**Comment by Himujjal** [comment]
@ajuvercr Will fix this on the next update. There is even a PR for this. Sorry everyone. I wasn't active in Github for a while now.
