### ISSUE TITLE
Reactive variable label parsing "$:"

### ISSUE THREAD

**Issue by garlandcrow** [Himujjal/tree-sitter-svelte#35]
I'm new to neovim so not sure how easy this is to add but is it possible to create a parsing for the label statement part of a reactive variable. I did this for VSCode so that I can syntax highlight the "$:" part of the line for visibility. Would be happy to help but not sure where to start...

**Comment by Himujjal** [comment]
Apologies for not seeing this issue on time. This can definitely be done. I will try to fix it ASAP
