### ISSUE TITLE
DIsable indent after style and script with 'o'

### ISSUE THREAD

**Issue by login6** [Himujjal/tree-sitter-svelte#37]
If i press o under end of tag - it creates extra indentation. How to remove it?
![Screenshot_2023-05-17_17-22-53](https://github.com/Himujjal/tree-sitter-svelte/assets/96973293/ba944f9a-7c01-4cc1-ba17-83e29f3c10b8)

**Comment by Himujjal** [comment]
This has to do with tree-sitter queries. Have to put in a PR to nvim-treesitter repo. Low priority for now.

**Comment by login6** [comment]
> fixed in [nvim-treesitter/nvim-treesitter#6035](https://github.com/nvim-treesitter/nvim-treesitter/pull/6035)

thanks
